services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - buildcalc_media_volume:/app/media
    depends_on:
      - db-check
    networks:
      - buildcalc_network

  db-check:
    image: postgres:16-alpine
    command: >
      sh -c "
        until pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER}; do
          echo 'Waiting for database...';
          sleep 2;
        done;
        echo 'Database is ready!';
      "
    env_file:
      - .env
    networks:
      - buildcalc_network

volumes:
  buildcalc_media_volume:

networks:
  buildcalc_network:
    driver: bridge
